# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/WORK_SPCAE/Vivado_Project/FrequencyHopping/FrequencyHopping.srcs/sources_1/bd/Frequency_Synthesizer/ip/Frequency_Synthesizer_dds_compiler_0_0/Frequency_Synthesizer_dds_compiler_0_0.xci
# IP: The module: 'Frequency_Synthesizer_dds_compiler_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/WORK_SPCAE/Vivado_Project/FrequencyHopping/FrequencyHopping.gen/sources_1/bd/Frequency_Synthesizer/ip/Frequency_Synthesizer_dds_compiler_0_0/Frequency_Synthesizer_dds_compiler_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Frequency_Synthesizer_dds_compiler_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/WORK_SPCAE/Vivado_Project/FrequencyHopping/FrequencyHopping.srcs/sources_1/bd/Frequency_Synthesizer/ip/Frequency_Synthesizer_dds_compiler_0_0/Frequency_Synthesizer_dds_compiler_0_0.xci
# IP: The module: 'Frequency_Synthesizer_dds_compiler_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/WORK_SPCAE/Vivado_Project/FrequencyHopping/FrequencyHopping.gen/sources_1/bd/Frequency_Synthesizer/ip/Frequency_Synthesizer_dds_compiler_0_0/Frequency_Synthesizer_dds_compiler_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Frequency_Synthesizer_dds_compiler_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
